branches:
  only:
  - master
language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: "Build"
      script: mvn clean package  
    - stage: "Analyze" 
      script: mvn sonar:sonar -Dsonar.projectKey=radsoulbeard_arkanum -Dsonar.organization=radsoulbeard-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=7bf6586cd151710318c8151346ebdc99a55e0fbd
   
    
